version: '3'
services:
    frontend:
        container_name: angular
        depends_on:
            - backend
        build:
            dockerfile: Dockerfile
            context: ./frontend/app
        ports:
            - '80:80'
    backend:
        container_name: django
        restart: unless-stopped
        build:
            context: ./backend
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - HOST=${HOST}
            - PORT=${PORT}
            - NAME=${NAME}
            - DB_USERNAME=${DB_USERNAME}
            - PASSWORD=${PASSWORD}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
            - PROD_MODE=${PROD_MODE}

        